### ISSUE TITLE
login with google fails

### ISSUE THREAD

**Issue by LaurensRietveld** [OpenTriply/YASGUI.legacy#289]
just hangs <br><br><strong>UserAgent</strong>: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36<br>

**Comment by apb2006** [comment]
url:
http://legacy.yasgui.org/Yasgui/openId?app-openid-auth=true&app-openid-name=https://www.google.com/accounts/o8/id&appBaseUrl=http://legacy.yasgui.org/

response
HTTP Status 500 - Login string probably caused an error. loginString = https://www.google.com/accounts/o8/id

type Status report

message Login string probably caused an error. loginString = https://www.google.com/accounts/o8/id

description The server encountered an internal error that prevented it from fulfilling this request.
Apache Tomcat/7.0.52 (Ubuntu)

**Comment by LaurensRietveld** [comment]
The legacy version of YASGUI still uses OpenID 2.0, which was supported as legacy by google, but seems to be completely discontinued now. 
I suggest using the newer version of YASGUI instead, as this legacy version won't receive any more updates
